language: "ko-KR"
early_access: false
reviews:
  request_changes_workflow: true # PR 승인/반려 권한
  high_level_summary: true # 요약글
  review_status: true
  collapse_walkthrough: false
  auto_revview: # 자동 리뷰
    enabled: true
    drafts: false
    base_branches:
      - "main"
      - "develop"
chat:
  auto_reply: true
